# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363a32b2c7e3854f52a09cb494469287f61411eec82819905477f70dedda24c4c8f47ccb4e56ef1c2d985bf7a2cde22d94159bc803409126765ebc97a7d123ea

test:
  secret_key_base: 462df562d7eb843bd016e968095cfacb8262b3b09dc0be2036ed89055daa5436d82f949401a1c43545ee8fa2019c0e6a84819aecfd85f3acf660f78fb1288321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
